<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>com.cuixing</groupId>
        <artifactId>cx-mes-cloud</artifactId>
        <version>1.0.1</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <modules>
        <module>cuixing-system</module>
        <module>cuixing-md</module>
        <module>cuixing-file</module>
        <module>cuixing-eq</module>
        <module>cuixing-job</module>
        <module>cuixing-qc</module>
        <module>cuixing-wms</module>
        <module>cuixing-gen</module>
        <module>cuixing-mes</module>
        <module>cuixing-mold</module>
        <module>cuixing-purchase</module>
        <module>cuixing-ws</module>
        <module>cuixing-sale</module>
        <module>cuixing-report</module>
        <module>cuixing-ecm</module>
        <module>cuixing-crm</module>
    </modules>

    <artifactId>cuixing-modules</artifactId>
    <packaging>pom</packaging>

    <description>
        cuixing-modules业务模块
    </description>

</project>
